<?xml version="1.0"?>

<?xml-stylesheet title="showSubscribed" href="subscribed.xsl" type="text/xsl"?>
<?xml-stylesheet title="showAvailable" href="available.xsl" type="text/xsl"?>
<?xml-stylesheet title="empty" href="empty.xsl" type="text/xsl"?>
<?xml-stylesheet title="unenroll" href="unenroll.xsl" type="text/xsl"?>
<?xml-stylesheet title="main" href="main.xsl" type="text/xsl"?>
<?xml-stylesheet title="search" href="search.xsl" type="text/xsl"?>

<document>
</document>
