/*
 * Copyright (C) 2007 Unicon, Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this distribution.  It is also available here:
 * http://www.fsf.org/licensing/licenses/gpl.html
 *
 * As a special exception to the terms and conditions of version 
 * 2 of the GPL, you may redistribute this Program in connection 
 * with Free/Libre and Open Source Software ("FLOSS") applications 
 * as described in the GPL FLOSS exception.  You should have received
 * a copy of the text describing the FLOSS exception along with this
 * distribution.
 */
package net.unicon.sdk.event;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Kevin Gary
 *
 * IEvent is the interface of any object encapsulating an event of
 * interest to be delivered by an IEventLogService 
 */
public interface IEvent extends Serializable, Comparable {

	/**
	 * Returns a String message set for the event
     * 
     * @return String the event's message
	 */
	public String getMessage();

    /**
     * Returns the timestamp indicating when this event was instantiated (not logged). 
     * An indication of when the event actually occurred.
     * 
     * @return java.util.Date date and time when this event was created. 
     * May be generated by the TimeService.getTimestamp method.
     */
    public Date getCreationDate();

}
