ALTER TABLE UP_USER ADD CONSTRAINT UP_USER_USER_NAME_UNIQ UNIQUE (USER_NAME);
ALTER TABLE UP_PERMISSION ADD CONSTRAINT UP_PERM_COMP_KEY UNIQUE (OWNER, PRINCIPAL_TYPE, PRINCIPAL_KEY, ACTIVITY, TARGET);
ALTER TABLE UPC_PERM_MGR ADD CONSTRAINT UP_PERM_MGR_COMP_KEY UNIQUE (IPERMISSIBLE_CLASS);
