<?xml version="1.0"?><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output method="html" indent="yes" />    <!-- Include Files --><xsl:include href="common.xsl"/>  <xsl:param name="current-error">null</xsl:param>    <!--<xsl:variable name="SELECTED_GROUP_ID"><xsl:value-of select="/announcement-edit/announcement/@category-id"/></xsl:variable>    <xsl:template match="/">        <textarea rows="4" cols="40">          <xsl:copy-of select = "*"/>           <parameter name="current_command"><xsl:value-of select="$current_command" /></parameter>          <parameter name="pageChannel"><xsl:value-of select="$pageChannel" /></parameter>          <parameter name="channel_admin"><xsl:value-of select="$channel_admin" /></parameter>           </textarea>            <xsl:apply-templates />    </xsl:template> -->        <xsl:template match="/owned-announcements">    
		<xsl:call-template name="links">
			<xsl:with-param name="curPage">edit</xsl:with-param>
		</xsl:call-template>
		
        <h2 class="page-title">Manage Announcements</h2>        
        <div class="bounding-box1">			<form action="{$baseActionURL}?command=delete-announcements" method="post">				<table cellpadding="0" cellspacing="0" border="0" width="100%">				<xsl:if test="$current-error != 'null'">				  <tr><td colspan="4" class="uportal-channel-warning">					<xsl:value-of select="$current-error"/>				  </td>				  </tr>				</xsl:if>					<tr>					  <th class="th-top">&#160;</th>					  <th class="th-top">&#160;</th>					  <th class="th-top">Announcement Message</th>					  <th class="th-top">Actions</th>					</tr>					<xsl:for-each select="announcement">					 <tr> 						   <td class="table-content-right" align="left" width="5%">							  <input type="checkbox" name="announcementIDs" value="{@announcement-id}"/>						   </td>          						   <td class="table-content-right" align="left" width="15%">							 <xsl:value-of select="@date" />						   </td>						   <td class="table-content-right" align="left" width="65%">									<xsl:call-template name='smarttext'>																<xsl:with-param name="body" select="announcement-body" />														</xsl:call-template>						   </td>						   <td class="table-content-right" align="left" nowrap="nowrap" width="15%">							  <a>								<xsl:attribute name="href"><xsl:value-of select="$baseActionURL"/>?command=edit-announcement&amp;announcement-id=<xsl:value-of select="@announcement-id"/></xsl:attribute>								Edit							  </a>							  &#160;|&#160;							  <a>							  <xsl:attribute name="href"><xsl:value-of select="$baseActionURL"/>?command=delete-announcement&amp;announcement-id=<xsl:value-of select="@announcement-id"/></xsl:attribute>							  Delete							  </a>						   </td>					</tr>					</xsl:for-each>					<tr>
					  <td colspan="4">
						<input class="uportal-button" type="button" value="Select All">
							<xsl:attribute  name = "onclick" >for(var i=0; i&lt; this.form.announcementIDs.length; i++){this.form.announcementIDs[i].checked=true}</xsl:attribute>
						</input>
						<xsl:text> </xsl:text>
						<input class="uportal-button" type="button" value="Deselect All">
							<xsl:attribute  name = "onclick" >for(var i=0; i&lt; this.form.announcementIDs.length; i++){this.form.announcementIDs[i].checked=false}</xsl:attribute>
						</input>
					  </td>
					</tr> 					<tr>					  <td colspan="4" class="table-nav">						<input name="command" value="Delete Selected" type="submit" class="uportal-button" title="Used to delete all of the announcements selected in the 'Select for Delete' column."/>						<input name="Cancel" value="Cancel" type="button" class="uportal-button" align="left" onclick="window.locationhref='{$baseActionURL}'" title="To cancel editing this announcement, returning to viewing the announcements"/>
					  </td>					</tr>				</table>			</form>		</div>
    </xsl:template>    <xsl:template match="announcement-body">        <xsl:apply-templates />    </xsl:template></xsl:stylesheet>