#!/bin/bash

if [ "$(egrep '<version>.*-rc-[0-9]+-SNAPSHOT</version>' pom.xml)" != "" ]; then
    echo "Project has already been promoted to a release candidate."
    exit
fi

mvn clean

modifications=$(svn status | egrep '^[\?MA]')
if [ "$modifications" != "" ]; then
    echo "There are local modifications. Aborting."
    echo $modifications
    exit
fi

sed -e 's~-SNAPSHOT</version>~-rc-1</version>~' blojsom/ant_pom.xml > blojsom/ant_pom.xml.tmp
mv blojsom/ant_pom.xml.tmp blojsom/ant_pom.xml

find . -name pom.xml | grep -v META-INF | while read pom; do
    sed -e 's~-SNAPSHOT</version>~-rc-1-SNAPSHOT</version>~' $pom > $pom.tmp
    mv $pom.tmp $pom
done

svn commit -m 'preparing release candidate' 

mvn install
mvn clean

mvn --batch-mode release:prepare -DpreparationGoals="clean install"

if [ $? -ne 0 ]; then
    exit
fi

#mvn release:perform -DuseReleaseProfile=false

#if [ $? -ne 0 ]; then
#    exit
#fi

release=$(egrep -- '-rc-[0-9]+</version>' blojsom/ant_pom.xml | sed -e 's~^.*<version>~~' -e 's~</version>.*$~~')
nextSnapshot=$(fgrep -- '-SNAPSHOT</version>' pom.xml | sed -e 's~^.*<version>~~' -e 's~</version>.*$~~')

sed -e "s~<version>$release</version>~<version>$nextSnapshot</version>~" blojsom/ant_pom.xml > blojsom/ant_pom.xml.tmp
mv blojsom/ant_pom.xml.tmp blojsom/ant_pom.xml

svn commit -m "adding next snapshot version ($nextSnapshot) after release candidate ($release)" blojsom/ant_pom.xml
