#!/bin/bash

if [ "$(egrep '<version>.*-rc-[0-9]+-SNAPSHOT</version>' pom.xml)" != "" ]; then
    echo "Project has been promoted to a release candidate. Run next-rc-release."
    exit
fi

mvn clean

modifications=$(svn status | egrep '^[\?MA]')
if [ "$modifications" != "" ]; then
    echo "There are local modifications. Aborting."
    echo $modifications
    exit
fi

sed -e 's~-SNAPSHOT</version>~</version>~' blojsom/ant_pom.xml > blojsom/ant_pom.xml.tmp
mv blojsom/ant_pom.xml.tmp blojsom/ant_pom.xml

svn commit -m 'preparing build' 

mvn install
mvn clean

mvn --batch-mode release:prepare -DpreparationGoals="clean install"

if [ $? -ne 0 ]; then
    exit
fi

#mvn release:perform -DuseReleaseProfile=false

#if [ $? -ne 0 ]; then
#    exit
#fi

release=$(egrep -- '[0-9]+\.[0-9]+\.[0-9]+</version>' blojsom/ant_pom.xml | sed -e 's~^.*<version>~~' -e 's~</version>.*$~~')
nextSnapshot=$(fgrep -- '-SNAPSHOT</version>' pom.xml | sed -e 's~^.*<version>~~' -e 's~</version>.*$~~')

sed -e "s~<version>$release</version>~<version>$nextSnapshot</version>~" blojsom/ant_pom.xml > blojsom/ant_pom.xml.tmp
mv blojsom/ant_pom.xml.tmp blojsom/ant_pom.xml

svn commit -m "adding next snapshot version ($nextSnapshot) after release ($release)" blojsom/ant_pom.xml 
